{
  "resources": [
    {
      "id": 1,
      "url": "",
      "public": true,
      "title": "Resetear Contraseña en de un protagonista",
      "description": "Proceso para resetear la contraseña de un protagonista desde cero en Campus Virtual (Moodle)",
      "shortDescription": "",
      "tags": "Docentes Virtuales",
      "type": "video/mp4",
      "createAt": "",
      "updatedAt": "",
      "createdBy": "",
      "updatedBy": "",
    },
    {
      "id": 2,
      "url": "",
      "public": true,
      "title": "",
      "description": "",
      "shortDescription": "",
      "tags": "",
      "type": "",
      "createAt": "",
      "updatedAt": "",
      "createdBy": "",
      "updatedBy": "",
    },
    {
      "id": 3,
      "url": "",
      "public": true,
      "title": "",
      "description": "",
      "shortDescription": "",
      "tags": "",
      "type": "",
      "createAt": "",
      "updatedAt": "",
      "createdBy": "",
      "updatedBy": "",
    },
  ]
}
